sudo: required

services:
    - docker

before_script:
    - sudo sysctl -w vm.max_map_count=262144
    - wget https://downloads.raspberrypi.org/raspbian_lite_latest -O /tmp/raspbian.zip
    - unzip /tmp/raspbian.zip -d ./raspian
    - docker-compose build
    - docker-compose up -d

script:
    - docker-compose run pi_shrink bash -c "fix_orphaned_inode_list ./raspian/*.img"
    - docker-compose run pi_shrink bash -c "pishrink ./raspian/*.img"
